<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hoja extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hoja_model');
    } 

    /*
     * Listing of hoja
     */
    function index()
    {
        $data['hoja'] = $this->Hoja_model->get_all_hoja();
        
        $data['_view'] = 'hoja/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new hoja
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipo' => $this->input->post('tipo'),
				'gramaje' => $this->input->post('gramaje'),
				'tamaño' => $this->input->post('tamaño'),
				'precio_h' => $this->input->post('precio_h'),
				'visible' => $this->input->post('visible'),
            );
            
            $hoja_id = $this->Hoja_model->add_hoja($params);
            redirect('hoja/index');
        }
        else
        {            
            $data['_view'] = 'hoja/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a hoja
     */
    function edit($id_hoja)
    {   
        // check if the hoja exists before trying to edit it
        $data['hoja'] = $this->Hoja_model->get_hoja($id_hoja);
        
        if(isset($data['hoja']['id_hoja']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipo' => $this->input->post('tipo'),
					'gramaje' => $this->input->post('gramaje'),
					'tamaño' => $this->input->post('tamaño'),
					'precio_h' => $this->input->post('precio_h'),
					'visible' => $this->input->post('visible'),
                );

                $this->Hoja_model->update_hoja($id_hoja,$params);            
                redirect('hoja/index');
            }
            else
            {
                $data['_view'] = 'hoja/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The hoja you are trying to edit does not exist.');
    } 

    /*
     * Deleting hoja
     */
    function remove($id_hoja)
    {
        $hoja = $this->Hoja_model->get_hoja($id_hoja);

        // check if the hoja exists before trying to delete it
        if(isset($hoja['id_hoja']))
        {
            $this->Hoja_model->delete_hoja($id_hoja);
            redirect('hoja/index');
        }
        else
            show_error('The hoja you are trying to delete does not exist.');
    }
    
}
