<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Impresora extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Impresora_model');
    } 

    /*
     * Listing of impresora
     */
    function index()
    {
        $data['impresora'] = $this->Impresora_model->get_all_impresora();
        
        $data['_view'] = 'impresora/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new impresora
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre_impresora' => $this->input->post('nombre_impresora'),
				'descripción' => $this->input->post('descripción'),
				'precio_i' => $this->input->post('precio_i'),
				'visible' => $this->input->post('visible'),
            );
            
            $impresora_id = $this->Impresora_model->add_impresora($params);
            redirect('impresora/index');
        }
        else
        {            
            $data['_view'] = 'impresora/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a impresora
     */
    function edit($id_impresora)
    {   
        // check if the impresora exists before trying to edit it
        $data['impresora'] = $this->Impresora_model->get_impresora($id_impresora);
        
        if(isset($data['impresora']['id_impresora']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre_impresora' => $this->input->post('nombre_impresora'),
					'descripción' => $this->input->post('descripción'),
					'precio_i' => $this->input->post('precio_i'),
					'visible' => $this->input->post('visible'),
                );

                $this->Impresora_model->update_impresora($id_impresora,$params);            
                redirect('impresora/index');
            }
            else
            {
                $data['_view'] = 'impresora/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The impresora you are trying to edit does not exist.');
    } 

    /*
     * Deleting impresora
     */
    function remove($id_impresora)
    {
        $impresora = $this->Impresora_model->get_impresora($id_impresora);

        // check if the impresora exists before trying to delete it
        if(isset($impresora['id_impresora']))
        {
            $this->Impresora_model->delete_impresora($id_impresora);
            redirect('impresora/index');
        }
        else
            show_error('The impresora you are trying to delete does not exist.');
    }
    
}
