<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pedido_model');
    } 

    /*
     * Listing of pedidos
     */
    function index()
    {
        $data['pedidos'] = $this->Pedido_model->get_all_pedidos();
        
        $data['_view'] = 'pedido/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pedido
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'cliente' => $this->input->post('cliente'),
				'teléfono' => $this->input->post('teléfono'),
				'cantidad' => $this->input->post('cantidad'),
				'hoja' => $this->input->post('hoja'),
				'impresora' => $this->input->post('impresora'),
				'servicio' => $this->input->post('servicio'),
				'estado' => $this->input->post('estado'),
				'monto_final' => $this->input->post('monto_final'),
				'descripción_tarea' => $this->input->post('descripción_tarea'),
				'fecha_entrada' => $this->input->post('fecha_entrada'),
				'visible' => $this->input->post('visible'),
            );
            
            $pedido_id = $this->Pedido_model->add_pedido($params);
            redirect('pedido/index');
        }
        else
        {            
            $data['_view'] = 'pedido/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pedido
     */
    function edit($id_pedido)
    {   
        // check if the pedido exists before trying to edit it
        $data['pedido'] = $this->Pedido_model->get_pedido($id_pedido);
        
        if(isset($data['pedido']['id_pedido']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'cliente' => $this->input->post('cliente'),
					'teléfono' => $this->input->post('teléfono'),
					'cantidad' => $this->input->post('cantidad'),
					'hoja' => $this->input->post('hoja'),
					'impresora' => $this->input->post('impresora'),
					'servicio' => $this->input->post('servicio'),
					'estado' => $this->input->post('estado'),
					'monto_final' => $this->input->post('monto_final'),
					'descripción_tarea' => $this->input->post('descripción_tarea'),
					'fecha_entrada' => $this->input->post('fecha_entrada'),
					'visible' => $this->input->post('visible'),
                );

                $this->Pedido_model->update_pedido($id_pedido,$params);            
                redirect('pedido/index');
            }
            else
            {
                $data['_view'] = 'pedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pedido you are trying to edit does not exist.');
    } 

    /*
     * Deleting pedido
     */
    function remove($id_pedido)
    {
        $pedido = $this->Pedido_model->get_pedido($id_pedido);

        // check if the pedido exists before trying to delete it
        if(isset($pedido['id_pedido']))
        {
            $this->Pedido_model->delete_pedido($id_pedido);
            redirect('pedido/index');
        }
        else
            show_error('The pedido you are trying to delete does not exist.');
    }
    
}
