<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Presupuesto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Presupuesto_model');
    } 

    /*
     * Listing of presupuesto
     */
    function index()
    {
        $data['presupuesto'] = $this->Presupuesto_model->get_all_presupuesto();
        
        $data['_view'] = 'presupuesto/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new presupuesto
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descuento' => $this->input->post('descuento'),
				'cantidad' => $this->input->post('cantidad'),
				'monto_final' => $this->input->post('monto_final'),
				'id_cliente' => $this->input->post('id_cliente'),
				'id_hoja' => $this->input->post('id_hoja'),
				'id_impresora' => $this->input->post('id_impresora'),
				'id_servicio' => $this->input->post('id_servicio'),
				'cliente' => $this->input->post('cliente'),
				'visible' => $this->input->post('visible'),
            );
            
            $presupuesto_id = $this->Presupuesto_model->add_presupuesto($params);
            redirect('presupuesto/index');
        }
        else
        {            
            $data['_view'] = 'presupuesto/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a presupuesto
     */
    function edit($id_presupuesto)
    {   
        // check if the presupuesto exists before trying to edit it
        $data['presupuesto'] = $this->Presupuesto_model->get_presupuesto($id_presupuesto);
        
        if(isset($data['presupuesto']['id_presupuesto']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descuento' => $this->input->post('descuento'),
					'cantidad' => $this->input->post('cantidad'),
					'monto_final' => $this->input->post('monto_final'),
					'id_cliente' => $this->input->post('id_cliente'),
					'id_hoja' => $this->input->post('id_hoja'),
					'id_impresora' => $this->input->post('id_impresora'),
					'id_servicio' => $this->input->post('id_servicio'),
					'cliente' => $this->input->post('cliente'),
					'visible' => $this->input->post('visible'),
                );

                $this->Presupuesto_model->update_presupuesto($id_presupuesto,$params);            
                redirect('presupuesto/index');
            }
            else
            {
                $data['_view'] = 'presupuesto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The presupuesto you are trying to edit does not exist.');
    } 

    /*
     * Deleting presupuesto
     */
    function remove($id_presupuesto)
    {
        $presupuesto = $this->Presupuesto_model->get_presupuesto($id_presupuesto);

        // check if the presupuesto exists before trying to delete it
        if(isset($presupuesto['id_presupuesto']))
        {
            $this->Presupuesto_model->delete_presupuesto($id_presupuesto);
            redirect('presupuesto/index');
        }
        else
            show_error('The presupuesto you are trying to delete does not exist.');
    }
    
}
