<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hoja_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hoja by id_hoja
     */
    function get_hoja($id_hoja)
    {
        return $this->db->get_where('hoja',array('id_hoja'=>$id_hoja))->row_array();
    }
        
    /*
     * Get all hoja
     */
    function get_all_hoja()
    {
        $this->db->order_by('id_hoja', 'desc');
        return $this->db->get('hoja')->result_array();
    }
        
    /*
     * function to add new hoja
     */
    function add_hoja($params)
    {
        $this->db->insert('hoja',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hoja
     */
    function update_hoja($id_hoja,$params)
    {
        $this->db->where('id_hoja',$id_hoja);
        return $this->db->update('hoja',$params);
    }
    
    /*
     * function to delete hoja
     */
    function delete_hoja($id_hoja)
    {
        return $this->db->delete('hoja',array('id_hoja'=>$id_hoja));
    }
}
