<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Impresora_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get impresora by id_impresora
     */
    function get_impresora($id_impresora)
    {
        return $this->db->get_where('impresora',array('id_impresora'=>$id_impresora))->row_array();
    }
        
    /*
     * Get all impresora
     */
    function get_all_impresora()
    {
        $this->db->order_by('id_impresora', 'desc');
        return $this->db->get('impresora')->result_array();
    }
        
    /*
     * function to add new impresora
     */
    function add_impresora($params)
    {
        $this->db->insert('impresora',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update impresora
     */
    function update_impresora($id_impresora,$params)
    {
        $this->db->where('id_impresora',$id_impresora);
        return $this->db->update('impresora',$params);
    }
    
    /*
     * function to delete impresora
     */
    function delete_impresora($id_impresora)
    {
        return $this->db->delete('impresora',array('id_impresora'=>$id_impresora));
    }
}
