<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pedido by id_pedido
     */
    function get_pedido($id_pedido)
    {
        return $this->db->get_where('pedidos',array('id_pedido'=>$id_pedido))->row_array();
    }
        
    /*
     * Get all pedidos
     */
    function get_all_pedidos()
    {
        $this->db->order_by('id_pedido', 'desc');
        return $this->db->get('pedidos')->result_array();
    }
        
    /*
     * function to add new pedido
     */
    function add_pedido($params)
    {
        $this->db->insert('pedidos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pedido
     */
    function update_pedido($id_pedido,$params)
    {
        $this->db->where('id_pedido',$id_pedido);
        return $this->db->update('pedidos',$params);
    }
    
    /*
     * function to delete pedido
     */
    function delete_pedido($id_pedido)
    {
        return $this->db->delete('pedidos',array('id_pedido'=>$id_pedido));
    }
}
