<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Presupuesto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get presupuesto by id_presupuesto
     */
    function get_presupuesto($id_presupuesto)
    {
        return $this->db->get_where('presupuesto',array('id_presupuesto'=>$id_presupuesto))->row_array();
    }
        
    /*
     * Get all presupuesto
     */
    function get_all_presupuesto()
    {
        $this->db->order_by('id_presupuesto', 'desc');
        return $this->db->get('presupuesto')->result_array();
    }
        
    /*
     * function to add new presupuesto
     */
    function add_presupuesto($params)
    {
        $this->db->insert('presupuesto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update presupuesto
     */
    function update_presupuesto($id_presupuesto,$params)
    {
        $this->db->where('id_presupuesto',$id_presupuesto);
        return $this->db->update('presupuesto',$params);
    }
    
    /*
     * function to delete presupuesto
     */
    function delete_presupuesto($id_presupuesto)
    {
        return $this->db->delete('presupuesto',array('id_presupuesto'=>$id_presupuesto));
    }
}
